version: '2'
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-cwj
    restart: always
    hostname: myRabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /root/volume/rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  #开放的端口依次是MQTT/TCP端口、MQTT/SSL端口、MQTT/WebSocket端口、HTTP API端口和Dashboard控制台端口
  emqx:
    image: emqx/emqx
    container_name: emqx-cwj
    restart: always
    hostname: myEmqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Chengw315
    ports:
      - 3306:3306
    volumes:
      - /root/volume/mysql/conf.d:/etc/mysql/conf.d
      - /root/volume/mysql/data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass chengw
    volumes:
      - /root/volume/redis/data:/data
      - /root/volume/redis/redis.conf:/etc/redis/redis.conf

  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    ports:
      - 8000:8000
    volumes:
      - /root/volume/mkdocs/my-project:/docs
    working_dir: /docs/my-project

  hexo:
    image: ipple1986/hexo
    container_name: hexo
    ports:
      - 4000:4000
    volumes:
      - /root/volume/hexo/docs/source/:/opt/hexo/ipple1986/source/
      - /root/volume/hexo/docs/_config.yml:/opt/hexo/ipple1986/_config.yml

  docsify:
    build:
      context: /root/dockerfiles/docsify
      dockerfile: Dockerfile
    container_name: docsify
    ports:
      - 3000:3000
    volumes:
      - /root/volume/docsify/docs/:/root/docs/

  gitbook:
    build:
      context: /root/dockerfiles/gitbook
      dockerfile: Dockerfile
      args:
        VERSION: 3.2.1
    container_name: gitbook
    ports:
      - 4001:4000
      - 35729:35729
    volumes:
      - /root/volume/gitbook/docs/:/srv/gitbook/

  docsite:
    build:
      context: /root/dockerfiles/docsite
      dockerfile: Dockerfile
    container_name: docsite
    ports:
      - 3001:8084
    volumes:
      - /root/volume/docsite/docs/:/root/my-project/

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - /root/volume/mongo/setup:/docker-entrypoint-initdb.d/
      - /root/volume/mongo/data/db:/data/db/
    environment:  # admin账号和密码
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: chengw

  jmxTest:
    build:
      context: /root/dockerfiles/jmxTest
      dockerfile: Dockerfile
    container_name: jmxTest
    ports:
      - 19728:19728

