// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Desktop/tasks.proto

package protobuf;

public final class TaskProto {
  private TaskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SubTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code SubTask}
   */
  public static final class SubTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SubTask)
      SubTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubTask.newBuilder() to construct.
    private SubTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubTask() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubTask();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.TaskProto.internal_static_SubTask_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.TaskProto.internal_static_SubTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.TaskProto.SubTask.class, protobuf.TaskProto.SubTask.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.TaskProto.SubTask)) {
        return super.equals(obj);
      }
      protobuf.TaskProto.SubTask other = (protobuf.TaskProto.SubTask) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.TaskProto.SubTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TaskProto.SubTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TaskProto.SubTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.TaskProto.SubTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.TaskProto.SubTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.TaskProto.SubTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.TaskProto.SubTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SubTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SubTask)
        protobuf.TaskProto.SubTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.TaskProto.internal_static_SubTask_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.TaskProto.internal_static_SubTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.TaskProto.SubTask.class, protobuf.TaskProto.SubTask.Builder.class);
      }

      // Construct using protobuf.TaskProto.SubTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.TaskProto.internal_static_SubTask_descriptor;
      }

      @Override
      public protobuf.TaskProto.SubTask getDefaultInstanceForType() {
        return protobuf.TaskProto.SubTask.getDefaultInstance();
      }

      @Override
      public protobuf.TaskProto.SubTask build() {
        protobuf.TaskProto.SubTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public protobuf.TaskProto.SubTask buildPartial() {
        protobuf.TaskProto.SubTask result = new protobuf.TaskProto.SubTask(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.TaskProto.SubTask) {
          return mergeFrom((protobuf.TaskProto.SubTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.TaskProto.SubTask other) {
        if (other == protobuf.TaskProto.SubTask.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.TaskProto.SubTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.TaskProto.SubTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SubTask)
    }

    // @@protoc_insertion_point(class_scope:SubTask)
    private static final protobuf.TaskProto.SubTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.TaskProto.SubTask();
    }

    public static protobuf.TaskProto.SubTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubTask>
        PARSER = new com.google.protobuf.AbstractParser<SubTask>() {
      @Override
      public SubTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubTask> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SubTask> getParserForType() {
      return PARSER;
    }

    @Override
    public protobuf.TaskProto.SubTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    java.util.List<SubTask>
        getSubTaskList();
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    protobuf.TaskProto.SubTask getSubTask(int index);
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    int getSubTaskCount();
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    java.util.List<? extends SubTaskOrBuilder>
        getSubTaskOrBuilderList();
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    protobuf.TaskProto.SubTaskOrBuilder getSubTaskOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Task)
      TaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      name_ = "";
      subTask_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Task();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                subTask_ = new java.util.ArrayList<SubTask>();
                mutable_bitField0_ |= 0x00000001;
              }
              subTask_.add(
                  input.readMessage(protobuf.TaskProto.SubTask.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          subTask_ = java.util.Collections.unmodifiableList(subTask_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.TaskProto.internal_static_Task_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.TaskProto.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.TaskProto.Task.class, protobuf.TaskProto.Task.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int SUBTASK_FIELD_NUMBER = 3;
    private java.util.List<SubTask> subTask_;
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    @Override
    public java.util.List<SubTask> getSubTaskList() {
      return subTask_;
    }
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    @Override
    public java.util.List<? extends SubTaskOrBuilder>
        getSubTaskOrBuilderList() {
      return subTask_;
    }
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    @Override
    public int getSubTaskCount() {
      return subTask_.size();
    }
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    @Override
    public protobuf.TaskProto.SubTask getSubTask(int index) {
      return subTask_.get(index);
    }
    /**
     * <code>repeated .SubTask subTask = 3;</code>
     */
    @Override
    public protobuf.TaskProto.SubTaskOrBuilder getSubTaskOrBuilder(
        int index) {
      return subTask_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      for (int i = 0; i < subTask_.size(); i++) {
        output.writeMessage(3, subTask_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      for (int i = 0; i < subTask_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, subTask_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.TaskProto.Task)) {
        return super.equals(obj);
      }
      protobuf.TaskProto.Task other = (protobuf.TaskProto.Task) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getId()
          != other.getId()) return false;
      if (!getSubTaskList()
          .equals(other.getSubTaskList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getSubTaskCount() > 0) {
        hash = (37 * hash) + SUBTASK_FIELD_NUMBER;
        hash = (53 * hash) + getSubTaskList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.TaskProto.Task parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TaskProto.Task parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TaskProto.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TaskProto.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TaskProto.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TaskProto.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TaskProto.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.TaskProto.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.TaskProto.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.TaskProto.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.TaskProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.TaskProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.TaskProto.Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Task)
        protobuf.TaskProto.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.TaskProto.internal_static_Task_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.TaskProto.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.TaskProto.Task.class, protobuf.TaskProto.Task.Builder.class);
      }

      // Construct using protobuf.TaskProto.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubTaskFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = 0;

        if (subTaskBuilder_ == null) {
          subTask_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          subTaskBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.TaskProto.internal_static_Task_descriptor;
      }

      @Override
      public protobuf.TaskProto.Task getDefaultInstanceForType() {
        return protobuf.TaskProto.Task.getDefaultInstance();
      }

      @Override
      public protobuf.TaskProto.Task build() {
        protobuf.TaskProto.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public protobuf.TaskProto.Task buildPartial() {
        protobuf.TaskProto.Task result = new protobuf.TaskProto.Task(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.id_ = id_;
        if (subTaskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            subTask_ = java.util.Collections.unmodifiableList(subTask_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.subTask_ = subTask_;
        } else {
          result.subTask_ = subTaskBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.TaskProto.Task) {
          return mergeFrom((protobuf.TaskProto.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.TaskProto.Task other) {
        if (other == protobuf.TaskProto.Task.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (subTaskBuilder_ == null) {
          if (!other.subTask_.isEmpty()) {
            if (subTask_.isEmpty()) {
              subTask_ = other.subTask_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSubTaskIsMutable();
              subTask_.addAll(other.subTask_);
            }
            onChanged();
          }
        } else {
          if (!other.subTask_.isEmpty()) {
            if (subTaskBuilder_.isEmpty()) {
              subTaskBuilder_.dispose();
              subTaskBuilder_ = null;
              subTask_ = other.subTask_;
              bitField0_ = (bitField0_ & ~0x00000001);
              subTaskBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubTaskFieldBuilder() : null;
            } else {
              subTaskBuilder_.addAllMessages(other.subTask_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.TaskProto.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.TaskProto.Task) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<SubTask> subTask_ =
        java.util.Collections.emptyList();
      private void ensureSubTaskIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          subTask_ = new java.util.ArrayList<SubTask>(subTask_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.TaskProto.SubTask, protobuf.TaskProto.SubTask.Builder, protobuf.TaskProto.SubTaskOrBuilder> subTaskBuilder_;

      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public java.util.List<SubTask> getSubTaskList() {
        if (subTaskBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subTask_);
        } else {
          return subTaskBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public int getSubTaskCount() {
        if (subTaskBuilder_ == null) {
          return subTask_.size();
        } else {
          return subTaskBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public protobuf.TaskProto.SubTask getSubTask(int index) {
        if (subTaskBuilder_ == null) {
          return subTask_.get(index);
        } else {
          return subTaskBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder setSubTask(
          int index, protobuf.TaskProto.SubTask value) {
        if (subTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubTaskIsMutable();
          subTask_.set(index, value);
          onChanged();
        } else {
          subTaskBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder setSubTask(
          int index, protobuf.TaskProto.SubTask.Builder builderForValue) {
        if (subTaskBuilder_ == null) {
          ensureSubTaskIsMutable();
          subTask_.set(index, builderForValue.build());
          onChanged();
        } else {
          subTaskBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder addSubTask(protobuf.TaskProto.SubTask value) {
        if (subTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubTaskIsMutable();
          subTask_.add(value);
          onChanged();
        } else {
          subTaskBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder addSubTask(
          int index, protobuf.TaskProto.SubTask value) {
        if (subTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubTaskIsMutable();
          subTask_.add(index, value);
          onChanged();
        } else {
          subTaskBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder addSubTask(
          protobuf.TaskProto.SubTask.Builder builderForValue) {
        if (subTaskBuilder_ == null) {
          ensureSubTaskIsMutable();
          subTask_.add(builderForValue.build());
          onChanged();
        } else {
          subTaskBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder addSubTask(
          int index, protobuf.TaskProto.SubTask.Builder builderForValue) {
        if (subTaskBuilder_ == null) {
          ensureSubTaskIsMutable();
          subTask_.add(index, builderForValue.build());
          onChanged();
        } else {
          subTaskBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder addAllSubTask(
          Iterable<? extends SubTask> values) {
        if (subTaskBuilder_ == null) {
          ensureSubTaskIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subTask_);
          onChanged();
        } else {
          subTaskBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder clearSubTask() {
        if (subTaskBuilder_ == null) {
          subTask_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          subTaskBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public Builder removeSubTask(int index) {
        if (subTaskBuilder_ == null) {
          ensureSubTaskIsMutable();
          subTask_.remove(index);
          onChanged();
        } else {
          subTaskBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public protobuf.TaskProto.SubTask.Builder getSubTaskBuilder(
          int index) {
        return getSubTaskFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public protobuf.TaskProto.SubTaskOrBuilder getSubTaskOrBuilder(
          int index) {
        if (subTaskBuilder_ == null) {
          return subTask_.get(index);  } else {
          return subTaskBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public java.util.List<? extends SubTaskOrBuilder>
           getSubTaskOrBuilderList() {
        if (subTaskBuilder_ != null) {
          return subTaskBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subTask_);
        }
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public protobuf.TaskProto.SubTask.Builder addSubTaskBuilder() {
        return getSubTaskFieldBuilder().addBuilder(
            protobuf.TaskProto.SubTask.getDefaultInstance());
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public protobuf.TaskProto.SubTask.Builder addSubTaskBuilder(
          int index) {
        return getSubTaskFieldBuilder().addBuilder(
            index, protobuf.TaskProto.SubTask.getDefaultInstance());
      }
      /**
       * <code>repeated .SubTask subTask = 3;</code>
       */
      public java.util.List<SubTask.Builder>
           getSubTaskBuilderList() {
        return getSubTaskFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.TaskProto.SubTask, protobuf.TaskProto.SubTask.Builder, protobuf.TaskProto.SubTaskOrBuilder>
          getSubTaskFieldBuilder() {
        if (subTaskBuilder_ == null) {
          subTaskBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protobuf.TaskProto.SubTask, protobuf.TaskProto.SubTask.Builder, protobuf.TaskProto.SubTaskOrBuilder>(
                  subTask_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          subTask_ = null;
        }
        return subTaskBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Task)
    }

    // @@protoc_insertion_point(class_scope:Task)
    private static final protobuf.TaskProto.Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.TaskProto.Task();
    }

    public static protobuf.TaskProto.Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      @Override
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    @Override
    public protobuf.TaskProto.Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubTask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023Desktop/tasks.proto\"#\n\007SubTask\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\";\n\004Task\022\014\n\004name\030\001 \001(\t" +
      "\022\n\n\002id\030\002 \001(\005\022\031\n\007subTask\030\003 \003(\0132\010.SubTaskB" +
      "\037\n\022protobufB\tTaskProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SubTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubTask_descriptor,
        new String[] { "Id", "Name", });
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Task_descriptor,
        new String[] { "Name", "Id", "SubTask", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
